---
title: "Accessing Zarr data from STAC (?) using Rarr (??)"
author: "Johannes Heisig"
date: "`r Sys.Date()`"
output: html_document
---

## Local Zarr with Rarr

Read the sample Zarr array provided with the Rarr package
```{r, message=FALSE, warning=FALSE}
#remotes::install_github("sharlagelfand/Rarr")
library(Rarr)
library(dplyr)

# Using a local file provided with the package
## This array has 3 dimensions
z1 <- system.file("extdata", "zarr_examples", "row-first",
  "int32.zarr",
  package = "Rarr"
)
zarr_overview(z1)


## read the entire array
z1_full = read_zarr_array(zarr_array_path = z1)
dim(z1_full)
```

Check the metadata of the Zarr array
```{r}
library(jsonlite)
array_meta = jsonlite::read_json(file.path(z1, ".zarray"))
array_meta$shape
```


Convert to a stars object
```{r}
library(stars)
(st_z1 = st_as_stars(z1_full))
plot(st_z1, breaks = "equal")
```

Next: Recognise the dimensions as stars coordinates...
```{r}
#(st_z1 = st_as_stars(z1_full))

```

## Remote Zarr with Rarr

```{r}
# get meta data for all assets in the zarr archive!
zarr_s3 = "https://objects.eodc.eu/e05ab01a9d56408d82ac32d69a5aae2a:sample-data/tutorial_data/cpm_v253/S2B_MSIL1C_20250113T103309_N0511_R108_T32TLQ_20250113T122458.zarr"

zarr_overview(zarr_s3, as_data_frame = T) |> 
  mutate(var = sub(zarr_s3, "", path)) |> 
  select(var, everything(), -path)  |> View()
```


```{r}
# This time point to a single band asset directly!
zarr_s3_b01 = "https://objects.eodc.eu/e05ab01a9d56408d82ac32d69a5aae2a:sample-data/tutorial_data/cpm_v253/S2B_MSIL1C_20250113T103309_N0511_R108_T32TLQ_20250113T122458.zarr/measurements/reflectance/r60m/b01"

zarr_overview(zarr_s3_b01)
```


```{r}
z_s3 = read_zarr_array(zarr_s3_b01, index=list(1:300, 1:300))
dim(z_s3)
```

Make a stars object
```{r}
zz = st_as_stars(z_s3)
plot(zz)

# get info from file name
utm_zone = 32
zarr_crs = st_crs(as.integer(paste0(258, utm_zone)))
var = "B01"
zz = st_as_stars(z_s3) |> 
  st_set_crs(zarr_crs) |> 
  st_set_dimensions(1:2, names = c("X","Y")) |> 
  setNames(var)
zz
plot(zz, axes = TRUE)
```

## Read and combine multiple bands??